name: GPT Issue Response

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Issue Text
      id: extract
      run: echo "Issue Text: \$(gh issue view \${{ github.event.issue.number }} --json body -q '.body')" >> \$GITHUB_ENV

    - name: Process Issue with langchain-0
      run: ./langchain-0.sh "\${{ env.Issue_Text }}" "additional input if needed" "output.txt"

    - name: Read and Format Response
      run: |
        RESPONSE=\$(cat output.txt)
        echo "Formatted Response: \$RESPONSE" >> \$GITHUB_ENV

    - name: Post Comment
      run: |
        gh issue comment \${{ github.event.issue.number }} --body "\${RESPONSE}"

